version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/miropet
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=7d
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - miropet-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=miropet
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - miropet-network

volumes:
  mongodb_data:

networks:
  miropet-network:
    driver: bridge
