name: Deploy to Ubuntu Server

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Navigate to project directory
            cd /home/ubuntu/projects/miropet-server

            # Pull latest changes
            git pull origin development

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Start the application using PM2
            pm2 restart miropet-api || pm2 start dist/server.js --name miropet-api

            echo "Deployment completed successfully!"
